apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jungschi
spec:
  sourceRepos:
    - 'git@github.com:denic0la/jungschi-infra.git'
    - 'https://github.com/DeNic0la/jungschi-infra.git'
  sourceNamespaces:
    - 'jungschi'
    - 'jungschi-dev'
  destinations: 
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
