---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pushover-token
  namespace: argocd
spec:
  encryptedData:
    pushover-token: AgDI0DlBRx5utf1aTcD3itMkhlHTxs3PJtgb1KI1lUlLgNME3025TBKUHqL9Iyfdctv6lLm7uCai2CgzNnc3YXVPiikw3NM3FdMGdeitU7SPhNg1/Hu+V9kLEkWgYjNd1JcM4qwFLL/JHvA4Bfd9SqoQ86UBZEo83ecLa4hHLRFXztAGHsif8ptcPQ7zOpfrKMLf07FFyZWaQdmmWA7N5CrnMD0jjugZ0OaK5tj5As++6f6TKCBn/y5GbI0mBkg22KX6ubli5CbjCZarqJK182edfxTdVCdt3GtLIUZnr+t8oFXFpPapAdLbCRValWVRiqdyutVNtqw6KvvtKWoa2TGtrDvtCw7OObqTXlyV44Q07uyz0a55+j0es2f79hX9Das4RPN3W94Ynj3cj9Wwbn7sKfZzAGLCqgb9P71clJYPcLUFWztPyTVf7tC78fDEoGd7jeX8rYEHOtZM+JzPr0EiihNL30DZNGQ52ITwNHb8bW4eosK/Z07/0mgb1M/TSd3mHdKlioiY8Eu6gzhB4Yn5N1AMNmlsx62HgxeeT0+7ga7lK0azB/rMqWtzKZmedkQ5KrSwT7/zjAAVXxoraPSQDKFsqo6yfhLrKlONOMEtKT0oBtXGWql7jLYlJ4dOaC23sBe7XT/YTKuTX/vLKdzFMdf4Knncb/dOnspyJS9MFB5CH/IAa+X9WTAbwxTHWVV+rNjf+PIG3/JG1v5iNyp86om3bYwQrZdA9ub3Uqk=
  template:
    metadata:
      name: pushover-token
      namespace: argocd
