apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: keycloak
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  source:
    repoURL: https://github.com/DeNic0la/keycloak-infra.git
    targetRevision: main
    path: '.'
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 3m
        factor: 3
        maxDuration: 5m
    automated:
      selfHeal: false
      allowEmpty: false
      prune: false
      enabled: true



  