apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: argocd:/ConfigMap:argocd/argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:nicola, applications, *, */*, allow
    p, role:nicola, projects, *, *, allow
    p, role:nicola, *, *, *, allow
    g, user:nicola, role:nicola
  policy.default: role:readonly
  policy.patchMode: 'glob'